---
{{- if .Values.components.reana_ui.cern_ropo }}
  {{- fail  "`components.reana_ui.cern_ropo` is deprecated, please use `components.reana_ui.privacy_notice_url` instead." }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: reana-config
  namespace: {{ .Release.Namespace }}
data:
  ui-config.yaml: |
    announcement: {{ .Values.components.reana_ui.announcement | quote | default "null"  }}
    polling_secs: {{ .Values.components.reana_ui.polling_secs | default 15 }}
    docs_url: {{ .Values.components.reana_ui.docs_url | quote | default "null" }}
    client_pyvenv: {{ .Values.components.reana_ui.client_pyvenv | quote | default "null" }}
    forum_url: {{ .Values.components.reana_ui.forum_url | quote | default "null" }}
    chat_url: {{ .Values.components.reana_ui.chat_url | quote | default "null" }}
    privacy_notice_url: {{ .Values.components.reana_ui.privacy_notice_url | quote | default "null"}}
    cern_sso: {{ .Values.components.reana_ui.cern_sso | default false }}
    login_provider_config: {{ .Values.login | toJson }}
    hide_signup: {{ .Values.components.reana_ui.hide_signup | default false }}
    admin_email: {{ .Values.notifications.email_config.receiver | quote | default "null" }}
    {{- if not (contains "forever" (.Values.interactive_sessions.maximum_inactivity_period | quote)) }}
    maximum_interactive_session_inactivity_period: {{ .Values.interactive_sessions.maximum_inactivity_period | quote | default "null" }}
    {{- else }}
    maximum_interactive_session_inactivity_period: null
    {{- end }}
    {{- if or (.Values.components.reana_ui.local_users) (eq (.Values.components.reana_ui.local_users | toString) "<nil>") }}
    local_users: true
    {{- else }}
    local_users: false
    {{- end }}
    {{- if or (.Values.components.reana_server.environment.REANA_USER_EMAIL_CONFIRMATION) (eq (.Values.components.reana_server.environment.REANA_USER_EMAIL_CONFIRMATION | toString) "<nil>") }}
    user_confirmation: true
    {{- else }}
    user_confirmation: false
    {{- end }}
    quota_enabled: {{ .Values.quota.enabled }}
    file_preview_size_limit: {{ int .Values.components.reana_ui.file_preview_size_limit }}
    launcher_examples:
    {{- range .Values.components.reana_ui.launcher_examples | default (list) }}
    - name: {{ .name | quote }}
      description: {{ .description | quote }}
      url: {{ .url | quote }}
      image_url: {{ .image_url | quote }}
      specification: {{ .specification | quote }}
    {{- end }}
