apiVersion: batch/v1
kind: Job
metadata:
  name: custom-job
spec:
  template:
    spec:
      containers:
      - name: create
        image: riga/py-sci
        resources:
          limits:
            memory: "256Mi"
        command: ["/bin/bash", "-c"]
        args:
          - |
            touch /data/results/outputfile.txt
            sh /data/code/script1.sh >> /data/results/outputfile.txt
            sh /data/code/script2.sh /data/data/input.txt /data/results/outputfile.txt
        volumeMounts:
        - mountPath: "/data"
          name: pv-storage
      restartPolicy: Never
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: local-pvc
