---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reana.prefixed_infrastructure_svaccount_name" . }}
{{- if .Values.namespace_runtime }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace_runtime }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reana.prefixed_runtime_svaccount_name" . }}
  namespace: {{ .Values.namespace_runtime }}
{{- end }}
